env:
    - TWISTED=Twisted=10.2.0
    - TWISTED=Twisted=12.3
    - TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk

language: python

python:
    - 2.7
    - pypy

install:
    - pip install -q $TWISTED --use-mirrors
    - pip install -r requirements.txt --use-mirrors
    - python setup.py -q install

script: trial mamba

notifications:
    email:
        - oscar.campos@member.fsf.org
